#!/usr/bin/env python3
"""08-22: RESUME BUILDER — 'the living map is my resume'.
Pulls the founder profile (data/job/resume_profile.json) + live empire numbers
(braxisai.com/ops/empire.json) and writes:
  - /var/www/braxis/resume/index.html   (the public page: braxisai.com/resume)
  - /var/www/braxis/resume/resume.md    (downloadable, paste-anywhere)
  - data/job/resume.json                (the machine-readable base the job
                                          watcher matches against)
Run: daily 05:00 cron (cronwrap).
"""
import json
import sys
import urllib.request
from pathlib import Path

BASE = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(BASE))
from shared import llm_router  # noqa: E402

WWW = Path("/var/www/braxis/resume")
PROFILE = BASE / "data" / "job" / "resume_profile.json"
OUT_JSON = BASE / "data" / "job" / "resume.json"
LOG = BASE / "logs" / "resume_build.log"


def log(*a):
    try:
        with open(LOG, "a") as f:
            f.write(f"[{__import__('datetime').datetime.now().isoformat()}] " + " ".join(map(str, a)) + "\n")
    except Exception:
        pass


def fetch_live_numbers():
    try:
        with urllib.request.urlopen("https://braxisai.com/ops/empire.json", timeout=20) as r:
            return json.loads(r.read())
    except Exception as e:
        log("empire.json fetch failed:", str(e)[:80])
        return {}


def main():
    profile = json.loads(PROFILE.read_text()) if PROFILE.exists() else {}
    live = fetch_live_numbers()
    # keep the machine-readable resume fresh: profile + live numbers
    out = dict(profile)
    out["live_numbers"] = live
    OUT_JSON.parent.mkdir(parents=True, exist_ok=True)
    OUT_JSON.write_text(json.dumps(out, indent=1))
    log("resume.json written")

    # LLM one-pager (honest — FILL IN items stay visible, no invented titles)
    prompt = (
        "Write a one-page resume for this person (a job applicant). Rules:\n"
        "- Mark any line containing 'FILL IN' exactly as-is (the owner fills those).\n"
        "- Absolutely no invented employers, titles, dates, or credentials.\n"
        "- Lead with a 3-line summary; then AI/Automation experience (this year);\n"
        "  then Property Management experience; then Skills; then Targets.\n"
        "- Keep it tight — under 450 words. Never invent dates: the AI section is the last year; leave other roles undated.\n"
        "Profile:\n" + json.dumps(profile, indent=1)
    )
    r = llm_router.call_llm(prompt, system_prompt=(
        "You are a resume writer. Honesty is non-negotiable — never fabricate. "
        "Plain markdown, no preamble, no thinking tags."),
        max_tokens=1500)
    md = (r.get("content") or "").strip()
    if not md or "<think>" in md[:200]:
        log("resume LLM output empty or think-prefixed — keeping previous")
        return 1

    WWW.mkdir(parents=True, exist_ok=True)
    (WWW / "resume.md").write_text(md)
    html = f"""<!DOCTYPE html><html lang="en"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Chris — Resume (Braxis AI founder)</title>
<style>
 body{{font-family:system-ui,Segoe UI,Roboto,sans-serif;max-width:760px;margin:0 auto;padding:2rem 1.2rem;background:#0f1117;color:#e6e8ee;line-height:1.55}}
 h1{{font-size:1.7rem;margin-bottom:.2rem}} .sub{{color:#8b93a7;margin-bottom:1.4rem}}
 a{{color:#6ab0f3}} h2{{border-bottom:1px solid #2a2f3a;padding-bottom:.3rem;margin-top:1.6rem;font-size:1.15rem}}
 .toplinks a{{margin-right:1rem}} .fill{{color:#e0a44f}}
</style></head><body>
<div class="toplinks">
<a href="/">Braxis AI</a><a href="/resume/resume.md">Download .md</a>
</div>
<h1>Chris — AI Automation Builder · Property Operations</h1>
<div class="sub">Vermont, USA · chris@braxisai.com · the living map: <a href="/">braxisai.com</a></div>
<article>{md}</article>
<hr><p class="sub" style="font-size:.85rem">Generated by the Braxis empire, {__import__('datetime').datetime.now().strftime('%Y-%m-%d')} · live numbers from the empire snapshot · <a href="/ops/jobs.html">job hunt desk</a></p>
</body></html>"""
    (WWW / "index.html").write_text(html)
    log("resume page + md written")
    return 0


if __name__ == "__main__":
    sys.exit(main())
